---
title: "Tidy Tuesday 2021-26 parks"
output:
  github_document: default
  html_notebook: default
  html_document:
    df_print: paged
    self_contained: false
bibliography: ["../tidytuesday.bib"]
nocite: '@*'
---

```{r setup}
library(tidyverse)
```

## Load the data

```{r load_data}
# Data source: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-22/parks.csv
parks_raw <- read_csv('data/parks.csv',
                col_types = cols(
                  year = col_factor(levels = NULL), # could cast as type date
                  rank = col_number(),
                  city = col_factor(levels = NULL), # for ease of processing
                  med_park_size_data = col_double(),
                  med_park_size_points = col_double(),
                  park_pct_city_data = col_character(), # trailing % sign
                  park_pct_city_points = col_double(),
                  pct_near_park_data = col_character(), # trailing % sign
                  pct_near_park_points = col_double(),
                  spend_per_resident_data = col_character(), # preceding $ sign
                  spend_per_resident_points = col_double(),
                  basketball_data = col_double(),
                  basketball_points = col_double(),
                  dogpark_data = col_double(),
                  dogpark_points = col_double(),
                  playground_data = col_double(),
                  playground_points = col_double(),
                  rec_sr_data = col_double(),
                  rec_sr_points = col_double(),
                  restroom_data = col_double(),
                  restroom_points = col_double(),
                  splashground_data = col_double(),
                  splashground_points = col_double(),
                  amenities_points = col_double(),
                  total_points = col_double(),
                  total_pct = col_double(),
                  city_dup = col_character(),
                  park_benches = col_double()
                )
              )
```

```{r clean_data}
parks <- parks_raw %>%
  mutate(
    park_pct_city_data = str_remove(park_pct_city_data, "%"), # remove %
    pct_near_park_data = str_remove(pct_near_park_data, "%"), # remove %
    spend_per_resident_data = str_remove(spend_per_resident_data, "\\$"), # remove $
    ) %>%
  mutate(
    park_pct_city_data = as.double(park_pct_city_data),
    pct_near_park_data = as.double(pct_near_park_data),
    spend_per_resident_data = as.double(spend_per_resident_data)
  ) %>%
  select(-city_dup)
```

Question 1: Is there a better way to do these two mutate calls as one?
