---
title: "Tidy Tuesday National Holidays"
output:
  html_document:
    df_print: paged
    self_contained: false
  github_document: default
  html_notebook: default
bibliography: ["../tidytuesday.bib"]
nocite: '@*'
---

# Setup

```{r setup, echo = "FALSE"}
library(tidytuesdayR)
tuesdata <- tt_load('2021-07-06')
holidays <- tuesdata$holidays

library(tidyverse)
library(lubridate)
library(sf)
library(spData)
library(countrycode)
library(tmap)

theme_set(theme_minimal())

```

# EDA
## Objective 1: Make a nice map of national independence days
## Objective 2: Make a network diagram of the empires

# Map

```{r}
holidays_clean <- holidays %>% 
    mutate(
      country = case_when(
        country == "Micronesia" ~ "Micronesia (Federated States)",
        TRUE ~ country
        ), 
      independence_from = case_when(
        independence_from == "Spanish Empire" ~ "Spain",
        independence_from == "Empire of Japan" ~ "Japan",
        independence_from == "American Colonization Society" ~ "United States",
        independence_from == "Kingdom of Great Britain" ~ "United Kingdom",
        independence_from == "United Kingdom and the British Mandate for Palestine" ~ "United Kingdom",
        independence_from == "Qing China[65][66]" ~ "China",
        independence_from == "Soviet Union[55]" ~ "Soviet Union",
        independence_from == "Soviet Union[80]" ~ "Soviet Union",
        independence_from == "Spanish Empire[72]" ~ "Spain",
        independence_from == "Empire of Japan and France" ~ "Japan and France",
        TRUE ~ independence_from
      ),  
      iso_2c = countrycode(country, origin = "country.name", destination = "iso2c")
      ) %>% 
    left_join(world, by = c("iso_2c" = "iso_a2"))
```


```{r}

holidays_map <- holidays_clean %>% 
  filter(continent == "Asia" & between(year, 1945, 1975)) %>% 
  st_as_sf() %>% 
  st_make_valid() %>% 
  st_cast("MULTIPOLYGON")

tm_shape(world[world$continent == "Asia", ]) +
  tm_borders(col = "grey") +
  tm_shape(holidays_map) +
    tm_borders(col = "black") +
    tm_fill(col = "independence_from") +
    tm_text(text = "name_long", size = 1, scale = 0.5, remove.overlap = TRUE)



```


```{r}

british_empire <- holidays_clean %>% 
  filter(independence_from == "United Kingdom") %>% 
  st_as_sf() %>% 
  st_make_valid() # %>% 
  #st_cast("MULTIPOLYGON")

tm_shape(world) +
  tm_borders(col = "grey") +
  tm_shape(british_empire) +
    tm_borders(col = "black") +
    tm_fill(col = "year")

```

